@startuml
left to right direction
actor User as u
actor Host as h
actor CaseWorker as c

rectangle Booking {
    usecase "Book Bed" as UC2
    usecase "Approve Booking" as UC3
    usecase "Reserve Bed" as UC4
    usecase "Check in" as UC5
    usecase "Check out" as UC6
    usecase "Approve Reservation" as UC7
}

u --> UC2
c --> UC3
h --> UC4
u --> UC5
u --> UC6
u --> UC7
@enduml